# !/usr/bin/env python

import ctypes
import numpy as np

from pyscf.fci import direct_spin1

from mrh.lib.helper import load_library
from mrh.my_pyscf.pbc.fci.direct_spin1_cplx import _unpack

# Author: Bhavnesh Jangid

libcplxcsf = load_library("libcplx_csf")

def sanity_check_link_index_without_trilidx(link_index, norb):
    '''
    Check that the link_index table is an ordinary orbital-index table, not a
    tril-index table.  The latter is incompatible with the native kernel below.
    '''
    link_index = np.asarray(link_index)
    if link_index.ndim != 3 or link_index.shape[2] != 4:
        msg = "Not a valid link_index table; expected shape (nstr, nlink, 4)"
        raise ValueError(msg)
    
    # In an ordinary link table, columns 0 and 1 are creation and destruction
    # orbital indices.  A tril-index table stores a packed pair index in column
    # 0 and is incompatible with the native kernel below.
    orbital_indices = link_index[..., :2]
    if np.any(orbital_indices < 0) or np.any(orbital_indices >= norb):
        msg = "Not a valid link_index table; " \
        "orbital indices must be in [0, norb)"
        raise ValueError(msg)

    return np.ascontiguousarray(link_index, dtype=np.int32)

def contract_1e(h1e, fcivec, norb, nelec, link_index=None):
    '''
    Contract a complex spin-separated one-electron Hamiltonian.
    args:
        h1e: np.ndarray of shape (2, norb, norb) 
            spin-separated one-electron Hamiltonian.
        fcivec: np.array of shape (nalpha, nbeta) or (nalpha*nbeta,) 
            CI vector
        norb: int
            active space orbitals
        nelec: tuple of int 
            number of electrons (nalpha, nbeta)
        link_index: Ordinary alpha/beta link tables generated by
            :func:`pyscf.fci.cistring.gen_linkstr_index`.
            without tril-indexing.  If None, the link tables are generated automatically.
    '''

    h1e = np.asarray(h1e)
    if h1e.shape != (2, norb, norb):
        msg = f"h1e must have shape (2, {norb}, {norb}); got {h1e.shape}"
        raise ValueError(msg)

    link_indexa, link_indexb = _unpack(norb, nelec, link_index)

    # Sanity check the link_index tables
    link_indexa = sanity_check_link_index_without_trilidx(link_indexa, norb)
    link_indexb = sanity_check_link_index_without_trilidx(link_indexb, norb)

    na, nlinka = link_indexa.shape[:2]
    nb, nlinkb = link_indexb.shape[:2]

    fcivec = np.asarray(fcivec)
    if fcivec.size != na * nb:
        msg = f"fcivec has {fcivec.size} elements; expected {na * nb}"
        raise ValueError(msg)

    h1e = np.ascontiguousarray(h1e, dtype=np.complex128)
    fcivec = np.ascontiguousarray(fcivec, dtype=np.complex128)
    ci1 = np.empty_like(fcivec)

    # Call the C function to perform the contraction
    # Currently, I have written a combined C function for both alpha and beta contractions. 
    # TODO: In future, I will write separate C functions for more modularity and clarity.

    libcplxcsf.FCIcontract_uhf_1e_cplx(
        h1e[0].ctypes.data_as(ctypes.c_void_p),
        h1e[1].ctypes.data_as(ctypes.c_void_p),
        fcivec.ctypes.data_as(ctypes.c_void_p),
        ci1.ctypes.data_as(ctypes.c_void_p),
        ctypes.c_int(norb),
        ctypes.c_int(na),
        ctypes.c_int(nb),
        ctypes.c_int(nlinka),
        ctypes.c_int(nlinkb),
        link_indexa.ctypes.data_as(ctypes.c_void_p),
        link_indexb.ctypes.data_as(ctypes.c_void_p),
    )
    return ci1.reshape(fcivec.shape).view(direct_spin1.FCIvector)
